config/routes.rb
Townent::Application.routes.draw do
  
  
  devise_for :people

  ## Server status
  resource :status, only: %w(show), controller: 'status'  
  
  
  ## Eventgroups CRUD
  resources :event_groups
    
  resources :genres, only: %w() do
    resources :event_groups, only: %w(index)
    resources :subcategories, only: %w() do
      resources :event_groups, only: %w(index)
    end
  end
  
  ## Venues CRUD
  resources :venues, except: %w(index)

  ## Search namespace
  namespace :search do
    resources :event_groups, only: %w(index)
    resources :events, only: %w(index)
    resources :venues, only: %w(index)
    resources :landing, only: %w(index)
    
    root to: 'landing#index'
  end
  
  ## Events CRUD
  resources :events
  
  
  ## City selection interface
  resources :cities, only: %w() do
    resources :events, only: %w(index)
    resources :genres, only: %w() do
      resources :events, only: %w(index)
      resources :categories, only: %w() do
        resources :events, only: %w(index)
      end
    end
  end
  
  
  namespace :admin do
    resources :categories
    resources :subcategories
  end

  root to: 'events#index'  
end

app/views/shared/_city_select.html.haml
#city-select
  .inner 
    .text-selector
      %span= 'Your city:'
      %a#city-name{href: '#'}= (@city.full_name if @city) || request_location.city
      %input{type: 'text', placeholder: (@city.full_name if @city) || request_location.city, style: 'display: none'}
      - unless params[:city_id] || session[:city_id]
        %a.button.active#yes{href: (city_events_url(@city) if @city)} Yes
        %a.button.active#no{href: '#'} No
      - cache do
        :coffeescript
          $ ->
            $('#city-name, #no').click (event) ->
              event.preventDefault()
              $("#city-select input").show().focus()
              $('#city-name, #no, #yes').hide()
            
            $('#yes').click (event) -> 
              $('#yes, #no').hide()
            
            $("#city-select input").autocomplete
              source: [#{City.only(:full_name, :_id).map{|c| {label: c.full_name, value: c._id}.to_json}.join(', ')}]
              focus: (event, ui) -> event.preventDefault()
              select: (event, el) -> window.location = ('/cities/' + el['item']['value'] + '/events')
      

    
    - if !@city and request_location
      %h4 Find out events in nearby cities:
      .nearby
        = raw nearby_cities.map{|c| "<a href=\"/cities/#{c.id}/events\">#{c.full_name}</a>"}.join(' ')


.notificator
  %h1
    - if !@city and request_location
      Find the cheapest ticket for
      %span= Event.count
      events in
      %span= City.count
      cities

    - if @city
      - if @category
        Find tickets for
        %span= @counter
        #{@category.sw_name.downcase} events in #{@city.full_name}

      - elsif @genre
        Find tickets for 
        %span= @counter
        #{@genre.sw_name.downcase} events in #{@city.full_name}


      - else
        Find tickets for 
        %span= @counter
        events in #{@city.full_name}

app/views/shared/_footer.html.haml
%footer#footer
  :javascript
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter21520519 = new Ya.Metrika({id:21520519,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  %noscript
    %div 
      %img{src: "//mc.yandex.ru/watch/21520519", style: "position:absolute; left:-9999px;", alt: ''}
  %ul<>
    %li
      %a{href: '#', onclick: '$(window).scrollTop(0)'}
        %img{src: '/assets/scroller.png', alt: 'Scroll top'}
    %li<>= link_to 'Events', '/'
    %li<>= link_to 'Artists', event_groups_url
    %li.search<>
      = form_for :q, url: '/search', method: :get do |f|
        = f.text_field :text, placeholder: 'Search by artist, event or even more...'
        
  - if person_signed_in?
    %ul<>
      %li<>= link_to 'Logout', destroy_person_session_path, method: :delete
      %li<>= link_to 'Categ', admin_categories_path
      %li<>= link_to 'Subcat', admin_subcategories_path
      %li<>
  %ul<>
    %li<>
      = link_to '©', new_person_session_path
      «Gdebilet», 2012—2013
    %li<>
    %li<>
      Дизайн сайта — 
      %a NewCult

app/views/shared/_header.html.haml
%nav.top-bar<>
  %ul<>
    %li<>
      %h1
        %a{href: '/'}
          %img{src: '/assets/logo.png', alt: 'Gdebilet'}
    %li<>
      %img{src: '/assets/events.png', alt: 'Events'}
      %a{href: '/'}Events
    %li<>
      %img{src: '/assets/artists.png', alt: 'Artists'}
      %a{href: '/event_groups'}Artists
    %li.search<>
      = form_for :q, url: '/search', method: :get do |f|
        = f.text_field :text, placeholder: 'Search by artist, event or even more...', id: Time.now.to_i