config/routes.rb
Townent::Application.routes.draw do
  
  
  devise_for :people

  ## Server status
  resource :status, only: %w(show), controller: 'status'  
  
  
  ## Eventgroups CRUD
  resources :event_groups
    
  resources :genres, only: %w() do
    resources :event_groups, only: %w(index)
    resources :subcategories, only: %w() do
      resources :event_groups, only: %w(index)
    end
  end
  
  ## Venues CRUD
  resources :venues, except: %w(index)

  ## Search namespace
  namespace :search do
    resources :event_groups, only: %w(index)
    resources :events, only: %w(index)
    resources :venues, only: %w(index)
    resources :landing, only: %w(index)
    
    root to: 'landing#index'
  end
  
  ## Events CRUD
  resources :events
  
  
  ## City selection interface
  resources :cities, only: %w() do
    resources :events, only: %w(index)
    resources :genres, only: %w() do
      resources :events, only: %w(index)
      resources :categories, only: %w() do
        resources :events, only: %w(index)
      end
    end
  end
  
  
  namespace :admin do
    resources :categories
    resources :subcategories
  end

  root to: 'events#index'  
end

app/models/category.rb
class Category
  include Mongoid::Document

  ## Common things
  field :_id, type: String, default: ->{sw_name.parameterize}
  
  
  ## Seatwave api
  field :sw_id, type: String
  field :sw_name


  ## Obtain initial set of eventgroups
  def fetch_event_groups
    Delayed::Job.enqueue EventGroupsFetcher.new(sw_id), priority: 10, queue: 'event_groups'
  end
  
  has_many :event_groups
  has_many :events
  
  belongs_to :subcategory
  belongs_to :genre
  index({genre_id: 1}, {unique: true, background: false})
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate_person!
  
  def index
    @categories = Category.all
  end
  
  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.haml
.notificator
  %h3 Categories

- @categories.each do |category|
  = form_for category, url: admin_category_path(category), method: :put, remote: true, html: {class: 'cool'} do |f|
    %fieldset<>
      .input-holder<>
        = f.label :subcategory_id, category.sw_name
        = f.select :subcategory_id, options_from_collection_for_select(category.genre.subcategories, :id, :name, (category.subcategory.id if category.subcategory)), {:include_blank => true}
      .controls
        = f.submit 'save'
  %hr
  
  
:coffeescript
  $ -> $('form.cool select').change ->
    $(this).siblings().css("color", "red")